<?php
$this->headLink()->appendStylesheet('/css/2col.css', 'screen');
if ($this->colourScheme) {
    $this->headLink()->appendStylesheet('/css/' . $this->colourScheme . '-colour-scheme.css', 'screen');
}
$this->layout()->title = $this->title;
?>

            <article class="col first-col">
                <h1><?php echo $this->escapeHtml($this->title) ?></h1>
                <?php echo $this->intro ?>
                <?php echo $this->body ?>
            </article>
            <section class="col last-col">
                <nav>
                    <?php
                    $active = $this->navigation('Navigation\Main')->findActive($this->navigation('Navigation\Main')->getContainer(), 1, null);
                    if (!isset($active['page']) || $active['page']->pages) :
                    $depth = isset($active['depth']) ? $active['depth'] : 1;
                    echo $this->navigation('Navigation\Main')->menu()->renderMenu(null, array(
                        'minDepth' => $depth,
                        'onlyActiveBranch' => true,
                        'renderParents' => false,
                        'ulClass' => 'sub-nav',
                    ));
                    endif; ?>
                </nav>
                <?php echo $this->rightColumn; ?>
            </section>
