<?php
if (empty($this->body)) {
    foreach ($this as $name => $value) {
        if (stripos($name, 'intro') !== false || stripos($name, 'body') !== false) {
            $this->body = $value;
            break;
        }
    }
}
?>
<li><a href="<?php echo $this->url('content', ['slug' => $this->name]); ?>"><?php echo $this->escapeHtml($this->title) ?></a><br>
<?php echo rtrim(trim($this->teaserTruncate($this->body, 200)), '.'); ?>...</li>
